<?php

namespace MustikaWijaya\PgsqlFdw\Services;

class SqlGenerator
{
    public function generate(
        string $source,
        string $dest,
        string $table,
        array $columns,
        string $targetSchema,
        string $serverName,
        string $remoteSchema = 'public',
        array $options = []
    ): string {
        $warnings = [];
        $columnDefs = [];

        foreach ($columns as $column) {
            $name = $column['name'];
            $type = $column['type'];
            $nullable = $column['nullable'] ?? true;
            $isUdt = $column['is_udt'] ?? false;

            if ($isUdt) {
                $warnings[] = "-- Warning: User-Defined Type (UDT) detected: {$type}. Ensure this type exists on the destination database.";
            }

            $def = "    \"{$name}\" {$type}";
            if (!$nullable) {
                $def .= " NOT NULL";
            }
            $columnDefs[] = $def;
        }

        $columnsSql = implode(",\n", $columnDefs);
        $optionsList = ["schema_name '{$remoteSchema}'", "table_name '{$table}'"];

        foreach ($options as $key => $val) {
            $optionsList[] = "{$key} '{$val}'";
        }
        $optionsSql = implode(", ", $optionsList);

        $warningHeader = !empty($warnings) ? implode("\n", $warnings) . "\n" : "";

        return <<<SQL
-- Generated by Laravel Postgres FDW
-- Source: {$source} | Dest: {$dest} | Table: {$table}
{$warningHeader}
DROP FOREIGN TABLE IF EXISTS {$targetSchema}.{$table};

CREATE FOREIGN TABLE {$targetSchema}.{$table} (
{$columnsSql}
)
SERVER {$serverName}
OPTIONS ({$optionsSql});
SQL;
    }
}
